# Target configurations
MCU_FAMILY := h7
MCU := H755
MCU_HAL := H755xx
CORE := m7
FLOAT_ABI := hard
FLOAT_ARCH := fpv4-sp-d16

# Sources
EXAMPLE_SOURCES += main.c
EXAMPLE_SOURCES += h7/perif_init.c

HAL_SOURCES += $(STM32HAL_REPO)/Src/stm32$(MCU_FAMILY)xx_hal.c
HAL_SOURCES += $(STM32HAL_REPO)/Src/stm32$(MCU_FAMILY)xx_hal_cortex.c
HAL_SOURCES += $(STM32HAL_REPO)/Src/stm32$(MCU_FAMILY)xx_hal_rcc.c
HAL_SOURCES += $(STM32HAL_REPO)/Src/stm32$(MCU_FAMILY)xx_hal_rcc_ex.c
HAL_SOURCES += $(STM32HAL_REPO)/Src/stm32$(MCU_FAMILY)xx_hal_flash.c
HAL_SOURCES += $(STM32HAL_REPO)/Src/stm32$(MCU_FAMILY)xx_hal_flash_ex.c
HAL_SOURCES += $(STM32HAL_REPO)/Src/stm32$(MCU_FAMILY)xx_hal_gpio.c
HAL_SOURCES += $(STM32HAL_REPO)/Src/stm32$(MCU_FAMILY)xx_hal_dma.c
HAL_SOURCES += $(STM32HAL_REPO)/Src/stm32$(MCU_FAMILY)xx_hal_tim.c
HAL_SOURCES += $(STM32HAL_REPO)/Src/stm32$(MCU_FAMILY)xx_hal_tim_ex.c

DRIVER_SOURCES += $(DRIVERS_DIR)/74HC595/74HC595.c

DEFINES += -DCORE_CM7

DEFINES += -DSERIAL_CLK_Pin=GPIO_PIN_12
DEFINES += -DSERIAL_DATA_Pin=GPIO_PIN_9
DEFINES += -DLATCH_CLK_Pin=GPIO_PIN_14

DEFINES += -DSERIAL_CLK_GPIO_Port=GPIOG
DEFINES += -DSERIAL_DATA_GPIO_Port=GPIOG
DEFINES += -DLATCH_CLK_GPIO_Port=GPIOE
