# Target configurations
MCU_FAMILY := f4
MCU := F411
MCU_HAL := F411xE
CORE := m4
FLOAT_ABI := hard
FLOAT_ARCH := fpv4-sp-d16

# Sources
EXAMPLE_SOURCES += main.c

HAL_SOURCES += $(STM32HAL_REPO)/Src/stm32$(MCU_FAMILY)xx_hal.c
HAL_SOURCES += $(STM32HAL_REPO)/Src/stm32$(MCU_FAMILY)xx_hal_cortex.c
HAL_SOURCES += $(STM32HAL_REPO)/Src/stm32$(MCU_FAMILY)xx_hal_rcc.c
HAL_SOURCES += $(STM32HAL_REPO)/Src/stm32$(MCU_FAMILY)xx_hal_flash.c
HAL_SOURCES += $(STM32HAL_REPO)/Src/stm32$(MCU_FAMILY)xx_hal_flash_ex.c
HAL_SOURCES += $(STM32HAL_REPO)/Src/stm32$(MCU_FAMILY)xx_hal_gpio.c
HAL_SOURCES += $(STM32HAL_REPO)/Src/stm32$(MCU_FAMILY)xx_hal_dma.c
HAL_SOURCES += $(STM32HAL_REPO)/Src/stm32$(MCU_FAMILY)xx_hal_tim.c
HAL_SOURCES += $(STM32HAL_REPO)/Src/stm32$(MCU_FAMILY)xx_hal_tim_ex.c

DRIVER_SOURCES += $(DRIVERS_DIR)/74HC595/74HC595.c

DEFINES += -DSERIAL_CLK_Pin=GPIO_PIN_8
DEFINES += -DSERIAL_DATA_Pin=GPIO_PIN_9
DEFINES += -DLATCH_CLK_Pin=GPIO_PIN_5

DEFINES += -DSERIAL_CLK_GPIO_Port=GPIOA
DEFINES += -DSERIAL_DATA_GPIO_Port=GPIOA
DEFINES += -DLATCH_CLK_GPIO_Port=GPIOB
